from django.urls import path

from .controllers import (
    ai_analyze,
    check_auth_status,
    complete_password_reset_view,
    complete_registration_view,
    confirm_password_reset_view,
    course_ai_user_detail,
    course_ai_users,
    course_ai_users_import,
    course_post_analytics,
    course_post_comments,
    course_post_detail,
    course_post_like,
    course_post_suggestions,
    course_posts,
    course_profile_view,
    create_course_view,
    dashboard_course_detail,
    dashboard_course_hashtag_detail,
    dashboard_course_student_detail,
    dashboard_summary,
    files_endpoint,
    follow_user,
    get_my_profile,
    join_course,
    list_courses,
    list_followers,
    list_following,
    list_managed_courses_view,
    list_user_courses_view,
    login_user,
    logout_view,
    messages_endpoint,
    notifications_endpoint,
    profile_detail,
    profile_options,
    profile_status,
    send_demo_email,
    send_password_reset_code,
    send_registration_code,
    set_user_admin,
    simulate_activity,
    submit_profile,
    update_course_view,
    update_display_name,
    upload_avatar,
    user_posts,
    user_posts_analytics,
    verify_registration_code_view,
)

urlpatterns = [
    path("auth/send-code/", send_registration_code, name="auth-send-code"),
    path("auth/verify-code/", verify_registration_code_view, name="auth-verify-code"),
    path("auth/set-password/", complete_registration_view, name="auth-set-password"),
    path("auth/login/", login_user, name="auth-login"),
    path("auth/logout/", logout_view, name="auth-logout"),
    path("auth/status/", check_auth_status, name="auth-status"),
    path("auth/reset/send-code/", send_password_reset_code, name="auth-reset-send"),
    path("auth/reset/verify-code/", confirm_password_reset_view, name="auth-reset-verify"),
    path("auth/reset/complete/", complete_password_reset_view, name="auth-reset-complete"),
    path("profile/status/", profile_status, name="profile-status"),
    path("profile/options/", profile_options, name="profile-options"),
    path("profile/me/", get_my_profile, name="profile-me"),
    path("profile/submit/", submit_profile, name="profile-submit"),
    path("profile/avatar/", upload_avatar, name="profile-avatar"),
    path("profile/display-name/", update_display_name, name="profile-display-name"),
    path("ai/analyze/", ai_analyze, name="ai-analyze"),
    path("users/<int:user_id>/profile/", profile_detail, name="profile-detail"),
    path("users/<int:user_id>/posts/", user_posts, name="user-posts"),
    path("users/<int:user_id>/posts/analytics/", user_posts_analytics, name="user-posts-analytics"),
    path("users/<int:user_id>/courses/", list_user_courses_view, name="user-courses"),
    path("users/<int:user_id>/admin/", set_user_admin, name="user-set-admin"),
    path("users/<int:user_id>/follow/", follow_user, name="user-follow"),
    path("users/<int:user_id>/following/", list_following, name="user-following"),
    path("users/<int:user_id>/followers/", list_followers, name="user-followers"),
    path("admin/dashboard/", dashboard_summary, name="admin-dashboard"),
    path(
        "admin/dashboard/courses/<int:course_id>/",
        dashboard_course_detail,
        name="admin-dashboard-course",
    ),
    path(
        "admin/dashboard/courses/<int:course_id>/hashtags/<str:hashtag>/",
        dashboard_course_hashtag_detail,
        name="admin-dashboard-course-hashtag",
    ),
    path(
        "admin/dashboard/courses/<int:course_id>/students/<int:student_id>/",
        dashboard_course_student_detail,
        name="admin-dashboard-course-student",
    ),
    path("courses/", list_courses, name="courses-list"),
    path("courses/join/", join_course, name="courses-join"),
    path("courses/create/", create_course_view, name="courses-create"),
    path("courses/<int:course_id>/", update_course_view, name="courses-update"),
    path("courses/<int:course_id>/profile/", course_profile_view, name="courses-profile"),
    path("courses/managed/", list_managed_courses_view, name="courses-managed"),
    path("courses/<int:course_id>/posts/", course_posts, name="course-posts"),
    path("courses/<int:course_id>/ai-users/", course_ai_users, name="course-ai-users"),
    path(
        "courses/<int:course_id>/ai-users/import/",
        course_ai_users_import,
        name="course-ai-users-import",
    ),
    path("courses/<int:course_id>/ai-users/<int:ai_user_id>/", course_ai_user_detail, name="course-ai-user-detail"),
    path("courses/<int:course_id>/posts/<int:post_id>/", course_post_detail, name="course-post-detail"),
    path("courses/<int:course_id>/posts/<int:post_id>/analytics/", course_post_analytics, name="course-post-analytics"),
    path("courses/<int:course_id>/posts/suggestions/", course_post_suggestions, name="course-post-suggestions"),
    path("courses/<int:course_id>/posts/<int:post_id>/like/", course_post_like, name="course-post-like"),
    path("courses/<int:course_id>/posts/<int:post_id>/comments/", course_post_comments, name="course-post-comments"),
    path("messages/", messages_endpoint, name="messages"),
    path("messages/send-email", send_demo_email, name="send-demo-email"),
    path("messages/files/", files_endpoint, name="files"),
    path("messages/notifications/", notifications_endpoint, name="notifications"),
    path(
        "messages/notifications/simulate",
        simulate_activity,
        name="notifications-simulate",
    ),
]
