--
-- PostgreSQL database dump
--

\restrict GmWEncarMs4aQe5h6moF1WsZhcavK66Xfmv03VqknMTsdQptdKVyXCFe02NAxeW

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO donut;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO donut;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO donut;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO donut;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO donut;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO donut;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_course; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_course (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    course_code character varying(32) NOT NULL,
    term character varying(32) NOT NULL,
    join_code character varying(16) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer
);


ALTER TABLE public.core_course OWNER TO donut;

--
-- Name: core_course_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_courseaiuser; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_courseaiuser (
    id bigint NOT NULL,
    username character varying(64) NOT NULL,
    display_name character varying(120) NOT NULL,
    gender character varying(32) NOT NULL,
    city character varying(64) NOT NULL,
    age_group character varying(32) NOT NULL,
    education_level character varying(64) NOT NULL,
    income_level character varying(64) NOT NULL,
    social_value smallint,
    sociability smallint,
    openness smallint,
    content_preference character varying(64) NOT NULL,
    interests jsonb NOT NULL,
    shopping_frequency character varying(64) NOT NULL,
    buying_behavior character varying(64) NOT NULL,
    decision_factor character varying(64) NOT NULL,
    shopping_preference character varying(64) NOT NULL,
    digital_time character varying(64) NOT NULL,
    interaction_style character varying(64) NOT NULL,
    influencer_type character varying(64) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    created_by_id integer,
    CONSTRAINT core_courseaiuser_openness_check CHECK ((openness >= 0)),
    CONSTRAINT core_courseaiuser_sociability_check CHECK ((sociability >= 0)),
    CONSTRAINT core_courseaiuser_social_value_check CHECK ((social_value >= 0))
);


ALTER TABLE public.core_courseaiuser OWNER TO donut;

--
-- Name: core_courseaiuser_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_courseaiuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_courseaiuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_courseaiuseridentity; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_courseaiuseridentity (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    ai_user_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_courseaiuseridentity OWNER TO donut;

--
-- Name: core_courseaiuseridentity_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_courseaiuseridentity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_courseaiuseridentity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursedashboardsnapshot; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursedashboardsnapshot (
    id bigint NOT NULL,
    data jsonb NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.core_coursedashboardsnapshot OWNER TO donut;

--
-- Name: core_coursedashboardsnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursedashboardsnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursedashboardsnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursehashtagdashboardsnapshot; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursehashtagdashboardsnapshot (
    id bigint NOT NULL,
    hashtag character varying(120) NOT NULL,
    data jsonb NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.core_coursehashtagdashboardsnapshot OWNER TO donut;

--
-- Name: core_coursehashtagdashboardsnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursehashtagdashboardsnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursehashtagdashboardsnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursemember; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursemember (
    id bigint NOT NULL,
    role character varying(16) NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_coursemember OWNER TO donut;

--
-- Name: core_coursemember_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursemember ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursemember_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursepost; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursepost (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id integer NOT NULL,
    course_id bigint NOT NULL,
    hashtags jsonb NOT NULL,
    mentions jsonb NOT NULL
);


ALTER TABLE public.core_coursepost OWNER TO donut;

--
-- Name: core_coursepost_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursepost ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursepost_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursepostattachment; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursepostattachment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    asset_id bigint NOT NULL,
    post_id bigint NOT NULL
);


ALTER TABLE public.core_coursepostattachment OWNER TO donut;

--
-- Name: core_coursepostattachment_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursepostattachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursepostattachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursepostcomment; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursepostcomment (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_coursepostcomment OWNER TO donut;

--
-- Name: core_coursepostcomment_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursepostcomment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursepostcomment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursepostlike; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursepostlike (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_coursepostlike OWNER TO donut;

--
-- Name: core_coursepostlike_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursepostlike ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursepostlike_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursepostmention; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursepostmention (
    id bigint NOT NULL,
    identifier character varying(80) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_coursepostmention OWNER TO donut;

--
-- Name: core_coursepostmention_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursepostmention ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursepostmention_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursepostview; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursepostview (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id integer
);


ALTER TABLE public.core_coursepostview OWNER TO donut;

--
-- Name: core_coursepostview_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursepostview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursepostview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_courseprofile; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_courseprofile (
    id bigint NOT NULL,
    avatar_url text NOT NULL,
    gender character varying(32) NOT NULL,
    city character varying(64) NOT NULL,
    age_group character varying(32) NOT NULL,
    education_level character varying(64) NOT NULL,
    income_level character varying(64) NOT NULL,
    social_value smallint NOT NULL,
    interests jsonb NOT NULL,
    sociability smallint NOT NULL,
    openness smallint NOT NULL,
    shopping_frequency character varying(64) NOT NULL,
    buying_behavior character varying(64) NOT NULL,
    decision_factor character varying(64) NOT NULL,
    shopping_preference character varying(64) NOT NULL,
    digital_time character varying(64) NOT NULL,
    content_preference character varying(64) NOT NULL,
    interaction_style character varying(64) NOT NULL,
    influencer_type character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT core_courseprofile_openness_check CHECK ((openness >= 0)),
    CONSTRAINT core_courseprofile_sociability_check CHECK ((sociability >= 0)),
    CONSTRAINT core_courseprofile_social_value_check CHECK ((social_value >= 0))
);


ALTER TABLE public.core_courseprofile OWNER TO donut;

--
-- Name: core_courseprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_courseprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_courseprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursestudentdashboardsnapshot; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_coursestudentdashboardsnapshot (
    id bigint NOT NULL,
    data jsonb NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    student_id integer NOT NULL
);


ALTER TABLE public.core_coursestudentdashboardsnapshot OWNER TO donut;

--
-- Name: core_coursestudentdashboardsnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_coursestudentdashboardsnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursestudentdashboardsnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_dashboardsnapshot; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_dashboardsnapshot (
    id bigint NOT NULL,
    data jsonb NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_dashboardsnapshot OWNER TO donut;

--
-- Name: core_dashboardsnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_dashboardsnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_dashboardsnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_mediaasset; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_mediaasset (
    id bigint NOT NULL,
    file character varying(100) NOT NULL,
    original_name character varying(255) NOT NULL,
    content_type character varying(128) NOT NULL,
    size bigint NOT NULL,
    uploaded_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_mediaasset OWNER TO donut;

--
-- Name: core_mediaasset_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_mediaasset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_mediaasset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_message; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_message (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_message OWNER TO donut;

--
-- Name: core_message_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_notification; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_notification (
    id bigint NOT NULL,
    recipient character varying(64) NOT NULL,
    actor character varying(64) NOT NULL,
    action character varying(32) NOT NULL,
    subject character varying(255) NOT NULL,
    body text NOT NULL,
    link character varying(200) NOT NULL,
    metadata jsonb NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_notification OWNER TO donut;

--
-- Name: core_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_postanalyticssnapshot; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_postanalyticssnapshot (
    id bigint NOT NULL,
    totals jsonb NOT NULL,
    sentiment_counts jsonb NOT NULL,
    sentiment_percentages jsonb NOT NULL,
    range_start date NOT NULL,
    range_end date NOT NULL,
    range_days integer NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    post_id bigint NOT NULL,
    CONSTRAINT core_postanalyticssnapshot_range_days_check CHECK ((range_days >= 0))
);


ALTER TABLE public.core_postanalyticssnapshot OWNER TO donut;

--
-- Name: core_postanalyticssnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_postanalyticssnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_postanalyticssnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_userfollow; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_userfollow (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    follower_id integer NOT NULL,
    target_id integer NOT NULL
);


ALTER TABLE public.core_userfollow OWNER TO donut;

--
-- Name: core_userfollow_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_userfollow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_userfollow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_userprofile; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.core_userprofile (
    id bigint NOT NULL,
    gender character varying(32) NOT NULL,
    city character varying(64) NOT NULL,
    age_group character varying(32) NOT NULL,
    education_level character varying(64) NOT NULL,
    income_level character varying(64) NOT NULL,
    social_value smallint NOT NULL,
    interests jsonb NOT NULL,
    sociability smallint NOT NULL,
    openness smallint NOT NULL,
    shopping_frequency character varying(64) NOT NULL,
    buying_behavior character varying(64) NOT NULL,
    decision_factor character varying(64) NOT NULL,
    shopping_preference character varying(64) NOT NULL,
    digital_time character varying(64) NOT NULL,
    content_preference character varying(64) NOT NULL,
    interaction_style character varying(64) NOT NULL,
    influencer_type character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    avatar_url text NOT NULL,
    CONSTRAINT core_userprofile_openness_check CHECK ((openness >= 0)),
    CONSTRAINT core_userprofile_sociability_check CHECK ((sociability >= 0)),
    CONSTRAINT core_userprofile_social_value_check CHECK ((social_value >= 0))
);


ALTER TABLE public.core_userprofile OWNER TO donut;

--
-- Name: core_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.core_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demo_mediaasset; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.demo_mediaasset (
    id bigint NOT NULL,
    file character varying(100) NOT NULL,
    original_name character varying(255) NOT NULL,
    content_type character varying(128) NOT NULL,
    size bigint NOT NULL,
    uploaded_at timestamp with time zone NOT NULL
);


ALTER TABLE public.demo_mediaasset OWNER TO donut;

--
-- Name: demo_mediaasset_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.demo_mediaasset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demo_mediaasset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demo_message; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.demo_message (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.demo_message OWNER TO donut;

--
-- Name: demo_message_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.demo_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demo_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demo_notification; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.demo_notification (
    id bigint NOT NULL,
    recipient character varying(64) NOT NULL,
    actor character varying(64) NOT NULL,
    action character varying(32) NOT NULL,
    subject character varying(255) NOT NULL,
    body text NOT NULL,
    link character varying(200) NOT NULL,
    metadata jsonb NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.demo_notification OWNER TO donut;

--
-- Name: demo_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.demo_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demo_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO donut;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO donut;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO donut;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: donut
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: donut
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO donut;

--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_course core_course_course_code_term_87824f15_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_course
    ADD CONSTRAINT core_course_course_code_term_87824f15_uniq UNIQUE (course_code, term);


--
-- Name: core_course core_course_join_code_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_course
    ADD CONSTRAINT core_course_join_code_key UNIQUE (join_code);


--
-- Name: core_course core_course_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_course
    ADD CONSTRAINT core_course_pkey PRIMARY KEY (id);


--
-- Name: core_courseaiuser core_courseaiuser_course_id_username_bdd1d63f_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuser
    ADD CONSTRAINT core_courseaiuser_course_id_username_bdd1d63f_uniq UNIQUE (course_id, username);


--
-- Name: core_courseaiuser core_courseaiuser_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuser
    ADD CONSTRAINT core_courseaiuser_pkey PRIMARY KEY (id);


--
-- Name: core_courseaiuseridentity core_courseaiuseridentity_ai_user_id_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuseridentity
    ADD CONSTRAINT core_courseaiuseridentity_ai_user_id_key UNIQUE (ai_user_id);


--
-- Name: core_courseaiuseridentity core_courseaiuseridentity_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuseridentity
    ADD CONSTRAINT core_courseaiuseridentity_pkey PRIMARY KEY (id);


--
-- Name: core_courseaiuseridentity core_courseaiuseridentity_user_id_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuseridentity
    ADD CONSTRAINT core_courseaiuseridentity_user_id_key UNIQUE (user_id);


--
-- Name: core_coursedashboardsnapshot core_coursedashboardsnapshot_course_id_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursedashboardsnapshot
    ADD CONSTRAINT core_coursedashboardsnapshot_course_id_key UNIQUE (course_id);


--
-- Name: core_coursedashboardsnapshot core_coursedashboardsnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursedashboardsnapshot
    ADD CONSTRAINT core_coursedashboardsnapshot_pkey PRIMARY KEY (id);


--
-- Name: core_coursehashtagdashboardsnapshot core_coursehashtagdashbo_course_id_hashtag_eca38bc3_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursehashtagdashboardsnapshot
    ADD CONSTRAINT core_coursehashtagdashbo_course_id_hashtag_eca38bc3_uniq UNIQUE (course_id, hashtag);


--
-- Name: core_coursehashtagdashboardsnapshot core_coursehashtagdashboardsnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursehashtagdashboardsnapshot
    ADD CONSTRAINT core_coursehashtagdashboardsnapshot_pkey PRIMARY KEY (id);


--
-- Name: core_coursemember core_coursemember_course_id_user_id_d2883df7_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursemember
    ADD CONSTRAINT core_coursemember_course_id_user_id_d2883df7_uniq UNIQUE (course_id, user_id);


--
-- Name: core_coursemember core_coursemember_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursemember
    ADD CONSTRAINT core_coursemember_pkey PRIMARY KEY (id);


--
-- Name: core_coursepost core_coursepost_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepost
    ADD CONSTRAINT core_coursepost_pkey PRIMARY KEY (id);


--
-- Name: core_coursepostattachment core_coursepostattachment_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostattachment
    ADD CONSTRAINT core_coursepostattachment_pkey PRIMARY KEY (id);


--
-- Name: core_coursepostcomment core_coursepostcomment_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostcomment
    ADD CONSTRAINT core_coursepostcomment_pkey PRIMARY KEY (id);


--
-- Name: core_coursepostlike core_coursepostlike_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostlike
    ADD CONSTRAINT core_coursepostlike_pkey PRIMARY KEY (id);


--
-- Name: core_coursepostlike core_coursepostlike_post_id_user_id_e46cbf33_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostlike
    ADD CONSTRAINT core_coursepostlike_post_id_user_id_e46cbf33_uniq UNIQUE (post_id, user_id);


--
-- Name: core_coursepostmention core_coursepostmention_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostmention
    ADD CONSTRAINT core_coursepostmention_pkey PRIMARY KEY (id);


--
-- Name: core_coursepostmention core_coursepostmention_post_id_user_id_8402bb62_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostmention
    ADD CONSTRAINT core_coursepostmention_post_id_user_id_8402bb62_uniq UNIQUE (post_id, user_id);


--
-- Name: core_coursepostview core_coursepostview_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostview
    ADD CONSTRAINT core_coursepostview_pkey PRIMARY KEY (id);


--
-- Name: core_courseprofile core_courseprofile_course_id_user_id_52fda187_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseprofile
    ADD CONSTRAINT core_courseprofile_course_id_user_id_52fda187_uniq UNIQUE (course_id, user_id);


--
-- Name: core_courseprofile core_courseprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseprofile
    ADD CONSTRAINT core_courseprofile_pkey PRIMARY KEY (id);


--
-- Name: core_coursestudentdashboardsnapshot core_coursestudentdashbo_course_id_student_id_63e215cc_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursestudentdashboardsnapshot
    ADD CONSTRAINT core_coursestudentdashbo_course_id_student_id_63e215cc_uniq UNIQUE (course_id, student_id);


--
-- Name: core_coursestudentdashboardsnapshot core_coursestudentdashboardsnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursestudentdashboardsnapshot
    ADD CONSTRAINT core_coursestudentdashboardsnapshot_pkey PRIMARY KEY (id);


--
-- Name: core_dashboardsnapshot core_dashboardsnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_dashboardsnapshot
    ADD CONSTRAINT core_dashboardsnapshot_pkey PRIMARY KEY (id);


--
-- Name: core_dashboardsnapshot core_dashboardsnapshot_user_id_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_dashboardsnapshot
    ADD CONSTRAINT core_dashboardsnapshot_user_id_key UNIQUE (user_id);


--
-- Name: core_mediaasset core_mediaasset_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_mediaasset
    ADD CONSTRAINT core_mediaasset_pkey PRIMARY KEY (id);


--
-- Name: core_message core_message_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_message
    ADD CONSTRAINT core_message_pkey PRIMARY KEY (id);


--
-- Name: core_notification core_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_notification
    ADD CONSTRAINT core_notification_pkey PRIMARY KEY (id);


--
-- Name: core_postanalyticssnapshot core_postanalyticssnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_postanalyticssnapshot
    ADD CONSTRAINT core_postanalyticssnapshot_pkey PRIMARY KEY (id);


--
-- Name: core_postanalyticssnapshot core_postanalyticssnapshot_post_id_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_postanalyticssnapshot
    ADD CONSTRAINT core_postanalyticssnapshot_post_id_key UNIQUE (post_id);


--
-- Name: core_userfollow core_userfollow_follower_id_target_id_4f389e6f_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_userfollow
    ADD CONSTRAINT core_userfollow_follower_id_target_id_4f389e6f_uniq UNIQUE (follower_id, target_id);


--
-- Name: core_userfollow core_userfollow_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_userfollow
    ADD CONSTRAINT core_userfollow_pkey PRIMARY KEY (id);


--
-- Name: core_userprofile core_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_pkey PRIMARY KEY (id);


--
-- Name: core_userprofile core_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: demo_mediaasset demo_mediaasset_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.demo_mediaasset
    ADD CONSTRAINT demo_mediaasset_pkey PRIMARY KEY (id);


--
-- Name: demo_message demo_message_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.demo_message
    ADD CONSTRAINT demo_message_pkey PRIMARY KEY (id);


--
-- Name: demo_notification demo_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.demo_notification
    ADD CONSTRAINT demo_notification_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_course_created_by_id_73ce404a; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_course_created_by_id_73ce404a ON public.core_course USING btree (created_by_id);


--
-- Name: core_course_join_code_35fe3e15_like; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_course_join_code_35fe3e15_like ON public.core_course USING btree (join_code varchar_pattern_ops);


--
-- Name: core_courseaiuser_course_id_5813cfaf; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_courseaiuser_course_id_5813cfaf ON public.core_courseaiuser USING btree (course_id);


--
-- Name: core_courseaiuser_created_by_id_cbaa9fb5; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_courseaiuser_created_by_id_cbaa9fb5 ON public.core_courseaiuser USING btree (created_by_id);


--
-- Name: core_coursehashtagdashboardsnapshot_course_id_30212e38; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursehashtagdashboardsnapshot_course_id_30212e38 ON public.core_coursehashtagdashboardsnapshot USING btree (course_id);


--
-- Name: core_coursemember_course_id_6fb3bc7b; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursemember_course_id_6fb3bc7b ON public.core_coursemember USING btree (course_id);


--
-- Name: core_coursemember_user_id_25859f54; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursemember_user_id_25859f54 ON public.core_coursemember USING btree (user_id);


--
-- Name: core_coursepost_author_id_2edb5b6b; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepost_author_id_2edb5b6b ON public.core_coursepost USING btree (author_id);


--
-- Name: core_coursepost_course_id_3e5e7e3e; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepost_course_id_3e5e7e3e ON public.core_coursepost USING btree (course_id);


--
-- Name: core_coursepostattachment_asset_id_dbe0d562; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostattachment_asset_id_dbe0d562 ON public.core_coursepostattachment USING btree (asset_id);


--
-- Name: core_coursepostattachment_post_id_3486d686; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostattachment_post_id_3486d686 ON public.core_coursepostattachment USING btree (post_id);


--
-- Name: core_coursepostcomment_post_id_6540dfba; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostcomment_post_id_6540dfba ON public.core_coursepostcomment USING btree (post_id);


--
-- Name: core_coursepostcomment_user_id_3aa5d47b; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostcomment_user_id_3aa5d47b ON public.core_coursepostcomment USING btree (user_id);


--
-- Name: core_coursepostlike_post_id_5a23d2fb; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostlike_post_id_5a23d2fb ON public.core_coursepostlike USING btree (post_id);


--
-- Name: core_coursepostlike_user_id_8bb79ebc; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostlike_user_id_8bb79ebc ON public.core_coursepostlike USING btree (user_id);


--
-- Name: core_coursepostmention_post_id_eaf457ed; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostmention_post_id_eaf457ed ON public.core_coursepostmention USING btree (post_id);


--
-- Name: core_coursepostmention_user_id_00be4830; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostmention_user_id_00be4830 ON public.core_coursepostmention USING btree (user_id);


--
-- Name: core_coursepostview_post_id_6f814e44; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostview_post_id_6f814e44 ON public.core_coursepostview USING btree (post_id);


--
-- Name: core_coursepostview_user_id_d42efbc4; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursepostview_user_id_d42efbc4 ON public.core_coursepostview USING btree (user_id);


--
-- Name: core_courseprofile_course_id_092112fe; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_courseprofile_course_id_092112fe ON public.core_courseprofile USING btree (course_id);


--
-- Name: core_courseprofile_user_id_050d6eca; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_courseprofile_user_id_050d6eca ON public.core_courseprofile USING btree (user_id);


--
-- Name: core_coursestudentdashboardsnapshot_course_id_1df165f5; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursestudentdashboardsnapshot_course_id_1df165f5 ON public.core_coursestudentdashboardsnapshot USING btree (course_id);


--
-- Name: core_coursestudentdashboardsnapshot_student_id_c2b159b8; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_coursestudentdashboardsnapshot_student_id_c2b159b8 ON public.core_coursestudentdashboardsnapshot USING btree (student_id);


--
-- Name: core_notification_recipient_1d9974ef; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_notification_recipient_1d9974ef ON public.core_notification USING btree (recipient);


--
-- Name: core_notification_recipient_1d9974ef_like; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_notification_recipient_1d9974ef_like ON public.core_notification USING btree (recipient varchar_pattern_ops);


--
-- Name: core_postanalyticssnapshot_course_id_e50903e8; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_postanalyticssnapshot_course_id_e50903e8 ON public.core_postanalyticssnapshot USING btree (course_id);


--
-- Name: core_userfollow_follower_id_992ededb; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_userfollow_follower_id_992ededb ON public.core_userfollow USING btree (follower_id);


--
-- Name: core_userfollow_target_id_84457a2f; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX core_userfollow_target_id_84457a2f ON public.core_userfollow USING btree (target_id);


--
-- Name: demo_notification_recipient_32e4abc7; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX demo_notification_recipient_32e4abc7 ON public.demo_notification USING btree (recipient);


--
-- Name: demo_notification_recipient_32e4abc7_like; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX demo_notification_recipient_32e4abc7_like ON public.demo_notification USING btree (recipient varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: donut
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_course core_course_created_by_id_73ce404a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_course
    ADD CONSTRAINT core_course_created_by_id_73ce404a_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_courseaiuser core_courseaiuser_course_id_5813cfaf_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuser
    ADD CONSTRAINT core_courseaiuser_course_id_5813cfaf_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_courseaiuser core_courseaiuser_created_by_id_cbaa9fb5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuser
    ADD CONSTRAINT core_courseaiuser_created_by_id_cbaa9fb5_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_courseaiuseridentity core_courseaiuseride_ai_user_id_eb5265b1_fk_core_cour; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuseridentity
    ADD CONSTRAINT core_courseaiuseride_ai_user_id_eb5265b1_fk_core_cour FOREIGN KEY (ai_user_id) REFERENCES public.core_courseaiuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_courseaiuseridentity core_courseaiuseridentity_user_id_4144ecf9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseaiuseridentity
    ADD CONSTRAINT core_courseaiuseridentity_user_id_4144ecf9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursedashboardsnapshot core_coursedashboard_course_id_9d32e646_fk_core_cour; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursedashboardsnapshot
    ADD CONSTRAINT core_coursedashboard_course_id_9d32e646_fk_core_cour FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursehashtagdashboardsnapshot core_coursehashtagda_course_id_30212e38_fk_core_cour; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursehashtagdashboardsnapshot
    ADD CONSTRAINT core_coursehashtagda_course_id_30212e38_fk_core_cour FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursemember core_coursemember_course_id_6fb3bc7b_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursemember
    ADD CONSTRAINT core_coursemember_course_id_6fb3bc7b_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursemember core_coursemember_user_id_25859f54_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursemember
    ADD CONSTRAINT core_coursemember_user_id_25859f54_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepost core_coursepost_author_id_2edb5b6b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepost
    ADD CONSTRAINT core_coursepost_author_id_2edb5b6b_fk_auth_user_id FOREIGN KEY (author_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepost core_coursepost_course_id_3e5e7e3e_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepost
    ADD CONSTRAINT core_coursepost_course_id_3e5e7e3e_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostattachment core_coursepostattac_asset_id_dbe0d562_fk_core_medi; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostattachment
    ADD CONSTRAINT core_coursepostattac_asset_id_dbe0d562_fk_core_medi FOREIGN KEY (asset_id) REFERENCES public.core_mediaasset(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostattachment core_coursepostattac_post_id_3486d686_fk_core_cour; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostattachment
    ADD CONSTRAINT core_coursepostattac_post_id_3486d686_fk_core_cour FOREIGN KEY (post_id) REFERENCES public.core_coursepost(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostcomment core_coursepostcomment_post_id_6540dfba_fk_core_coursepost_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostcomment
    ADD CONSTRAINT core_coursepostcomment_post_id_6540dfba_fk_core_coursepost_id FOREIGN KEY (post_id) REFERENCES public.core_coursepost(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostcomment core_coursepostcomment_user_id_3aa5d47b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostcomment
    ADD CONSTRAINT core_coursepostcomment_user_id_3aa5d47b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostlike core_coursepostlike_post_id_5a23d2fb_fk_core_coursepost_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostlike
    ADD CONSTRAINT core_coursepostlike_post_id_5a23d2fb_fk_core_coursepost_id FOREIGN KEY (post_id) REFERENCES public.core_coursepost(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostlike core_coursepostlike_user_id_8bb79ebc_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostlike
    ADD CONSTRAINT core_coursepostlike_user_id_8bb79ebc_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostmention core_coursepostmention_post_id_eaf457ed_fk_core_coursepost_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostmention
    ADD CONSTRAINT core_coursepostmention_post_id_eaf457ed_fk_core_coursepost_id FOREIGN KEY (post_id) REFERENCES public.core_coursepost(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostmention core_coursepostmention_user_id_00be4830_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostmention
    ADD CONSTRAINT core_coursepostmention_user_id_00be4830_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostview core_coursepostview_post_id_6f814e44_fk_core_coursepost_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostview
    ADD CONSTRAINT core_coursepostview_post_id_6f814e44_fk_core_coursepost_id FOREIGN KEY (post_id) REFERENCES public.core_coursepost(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursepostview core_coursepostview_user_id_d42efbc4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursepostview
    ADD CONSTRAINT core_coursepostview_user_id_d42efbc4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_courseprofile core_courseprofile_course_id_092112fe_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseprofile
    ADD CONSTRAINT core_courseprofile_course_id_092112fe_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_courseprofile core_courseprofile_user_id_050d6eca_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_courseprofile
    ADD CONSTRAINT core_courseprofile_user_id_050d6eca_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursestudentdashboardsnapshot core_coursestudentda_course_id_1df165f5_fk_core_cour; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursestudentdashboardsnapshot
    ADD CONSTRAINT core_coursestudentda_course_id_1df165f5_fk_core_cour FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursestudentdashboardsnapshot core_coursestudentda_student_id_c2b159b8_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_coursestudentdashboardsnapshot
    ADD CONSTRAINT core_coursestudentda_student_id_c2b159b8_fk_auth_user FOREIGN KEY (student_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dashboardsnapshot core_dashboardsnapshot_user_id_e9102aa4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_dashboardsnapshot
    ADD CONSTRAINT core_dashboardsnapshot_user_id_e9102aa4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_postanalyticssnapshot core_postanalyticssn_post_id_ef1cff51_fk_core_cour; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_postanalyticssnapshot
    ADD CONSTRAINT core_postanalyticssn_post_id_ef1cff51_fk_core_cour FOREIGN KEY (post_id) REFERENCES public.core_coursepost(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_postanalyticssnapshot core_postanalyticssnapshot_course_id_e50903e8_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_postanalyticssnapshot
    ADD CONSTRAINT core_postanalyticssnapshot_course_id_e50903e8_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userfollow core_userfollow_follower_id_992ededb_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_userfollow
    ADD CONSTRAINT core_userfollow_follower_id_992ededb_fk_auth_user_id FOREIGN KEY (follower_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userfollow core_userfollow_target_id_84457a2f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_userfollow
    ADD CONSTRAINT core_userfollow_target_id_84457a2f_fk_auth_user_id FOREIGN KEY (target_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userprofile core_userprofile_user_id_5141ad90_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_user_id_5141ad90_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: donut
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict GmWEncarMs4aQe5h6moF1WsZhcavK66Xfmv03VqknMTsdQptdKVyXCFe02NAxeW

